language: go

sudo: required

dist: trusty

go:
- 1.7.3

go_import_path: github.com/travis-ci/artifacts-v2

services:
- postgresql
- docker # just want to use GCE worker

env:
  global:
  - GIN_MODE=test
  - AWS_ACCESS_KEY_ID=AKID0987654321
  - AWS_SECRET_ACCESS_KEY=NOT-MY-SECRET

before_script:
- psql -c 'CREATE DATABASE test_artifacts;' -U postgres
- psql -f store/ddl/1.sql -d test_artifacts -U postgres
- psql -c "INSERT INTO artifacts (build_id, path, s3_object_key) VALUES ('foo', '/bar', 'fake_key');" -d test_artifacts -U postgres

script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- goveralls
