language: go

sudo: required

dist: trusty

go:
- 1.7.3

go_import_path: github.com/travis-ci/artifacts-v2

services:
- postgresql
- docker

env:
  global:
  - GIN_MODE=test
  - AWS_ACCESS_KEY_ID=AKID0987654321
  - AWS_SECRET_ACCESS_KEY=NOT-MY-SECRET
  - DATABASE_URI='db:pg://postgres@localhost:5432/test_artifacts'

before_script:
- psql -c 'CREATE DATABASE test_artifacts;' -U postgres
- docker run -v $(pwd):/src:ro -t --rm --network=host docteurklein/sqitch:pgsql deploy ${DATABASE_URI}
- docker run -v $(pwd):/src:ro -t --rm --network=host docteurklein/sqitch:pgsql verify ${DATABASE_URI}
- psql -c "INSERT INTO artifacts_v2.artifacts (build_id, path, s3_object_key) VALUES ('foo', '/bar', 'fake_key');" -d test_artifacts -U postgres
- openssl genrsa -out private_key.pem 2048
- openssl rsa -in private_key.pem -pubout -out public_key.pem
- export JWT_PRIVATE_KEY_PATH=$(pwd)/private_key.pem
- export JWT_PUBLIC_KEY="$(cat public_key.pem)"

script: make

before_deploy:
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
- sudo make install_kubectl

deploy:
- provider: script
  script: make TAG=${TRAVIS_BRANCH} release deploy
  skip_cleanup: true
  on:
    branch: master
