---
apiVersion: v1
kind: Service
metadata:
  name: artifacts
  labels:
    run: artifacts
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: artifacts-v2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifacts
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: artifacts-v2
    spec:
      containers:
      - name: server
        image: shawnzhu/artifacts-v2:kube
        env:
        - name: SERVER_ADDR
          value: ":443"
        - name: SERVER_CERT
          value: /etc/travis-artifacts/tls.crt
        - name: SERVER_KEY
          value: /etc/travis-artifacts/tls.key
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: "/etc/travis-artifacts"
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: artifacts-v2
