---
apiVersion: v1
kind: Service
metadata:
  name: artifacts
  labels:
    run: artifacts
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: artifacts-v2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifacts
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: artifacts-v2
    spec:
      containers:
      - name: server
        image: shawnzhu/artifacts-v2:deployment
        ports:
        - containerPort: 8080
